  0%|                                                                                                                                     | 0/2 [00:00<?, ?it/s]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/generation/utils.py:2109: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/grpo_tracking.py", line 258, in <module>
    main(script_args, training_args, model_args)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/grpo_tracking.py", line 248, in main
    trainer.train()
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 2243, in train
    return inner_training_loop(
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 2550, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 3700, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/trainer/grpo_trainer_tracking.py", line 365, in compute_loss
    prompt_completion_ids = unwrapped_model.generate(**generation_inputs, generation_config=self.generation_config)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/generation/utils.py", line 2219, in generate
    input_ids, model_kwargs = self._expand_inputs_for_generation(
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 2097, in _expand_inputs_for_generation
    model_kwargs = _expand_dict_for_generation_visual(model_kwargs)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 2049, in _expand_dict_for_generation_visual
    samples = torch.split(image_grid_thw, list(image_nums))
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/functional.py", line 207, in split
    return tensor.split(split_size_or_sections, dim)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/_tensor.py", line 983, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 12 (input tensor's size at dimension 0), but got split_sizes=[0, 0, 0, 0]
Traceback (most recent call last):
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/lihaobo/.vscode-server/extensions/ms-python.debugpy-2025.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/grpo_tracking.py", line 258, in <module>
    main(script_args, training_args, model_args)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/grpo_tracking.py", line 248, in main
    trainer.train()
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 2243, in train
    return inner_training_loop(
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 2550, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/trainer.py", line 3700, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/data1/lihaobo/tracking/rft/src/virft/src/open_r1/trainer/grpo_trainer_tracking.py", line 365, in compute_loss
    prompt_completion_ids = unwrapped_model.generate(**generation_inputs, generation_config=self.generation_config)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/generation/utils.py", line 2219, in generate
    input_ids, model_kwargs = self._expand_inputs_for_generation(
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 2097, in _expand_inputs_for_generation
    model_kwargs = _expand_dict_for_generation_visual(model_kwargs)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 2049, in _expand_dict_for_generation_visual
    samples = torch.split(image_grid_thw, list(image_nums))
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/functional.py", line 207, in split
    return tensor.split(split_size_or_sections, dim)
  File "/home/lihaobo/miniconda3/envs/track/lib/python3.10/site-packages/torch/_tensor.py", line 983, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 12 (input tensor's size at dimension 0), but got split_sizes=[0, 0, 0, 0]
